EM.Web/Models/ErrorViewModel.cs
namespace EM.Web.Models;

public class ErrorViewModel
{
	public string? RequestId { get; set; }

	public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

EM.Web/Controllers/AlunoController.cs
using EM.Domain;
using EM.Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace EM.Web.Controllers;

public class AlunoController : Controller
{
	private readonly IRepositorioAbstrato<Aluno> _repositorioAlunoAbstratro;
	private readonly IRepositorioAbstrato<Cidade> _repositorioCidade;
	private readonly IRepositorioAluno<Aluno> _repositorioAluno;

	public AlunoController(IRepositorioAbstrato<Aluno> repositorioAluno, IRepositorioAbstrato<Cidade> repositorioCidade, IRepositorioAluno<Aluno> repositorioRemove)
	{
		_repositorioAlunoAbstratro = repositorioAluno;
		_repositorioCidade = repositorioCidade;
		_repositorioAluno = repositorioRemove;
	}

	public IActionResult CadastreAluno(int? id)
	{
		ViewBag.Cidades = _repositorioCidade.GetAll().ToList();
		if (id != null)
		{
			Aluno? aluno = _repositorioAlunoAbstratro.Get(c => c.Matricula == id).FirstOrDefault();

			ViewBag.IsEdicao = true;
			return View(aluno);
		}
		ViewBag.IsEdicao = false;
		return View(new Aluno());

	}

	[HttpPost]
	public IActionResult CadastreAluno(Aluno aluno)
	{
		if (ModelState.IsValid)
		{
			if (aluno.Matricula > 0)
			{
				_repositorioAlunoAbstratro.Update(aluno);
			}
			else
			{
				_repositorioAlunoAbstratro.Add(aluno);
			}

			return RedirectToAction("Index", "Home");
		}
		ViewBag.IsEdicao = aluno.Matricula > 0;
		ViewBag.Cidades = _repositorioCidade.GetAll().ToList();
		return View(aluno);
	}

	[HttpPost]
	public IActionResult RemoveAluno(Aluno aluno)
	{
		_repositorioAluno.Remove(aluno);
		return RedirectToAction("Index", "Home");
	}

	[HttpPost]
	public ActionResult Pesquise(string TermoPesquisa, string TipoPesquisa)
	{
		if (TipoPesquisa != null)
		{
			if (TipoPesquisa.Equals("matricula", StringComparison.CurrentCultureIgnoreCase) && int.TryParse(TermoPesquisa, out int matricula))
			{
				Aluno aluno = _repositorioAluno.GetByMatricula(matricula);

				IEnumerable<Aluno> alunos = aluno != null ? new List<Aluno> { aluno } : [];
				return View("Views/Home/Index.cshtml", alunos);
			}
			else if (TipoPesquisa.Equals("nome", StringComparison.CurrentCultureIgnoreCase))
			{
				IEnumerable<Aluno> alunos = _repositorioAluno.GetByContendoNoNome(TermoPesquisa);
				return View("Views/Home/Index.cshtml", alunos);
			}
		}
		return View("Views/Home/Index.cshtml", new List<Aluno>());
	}
}

EM.Web/Controllers/CidadeController.cs
using EM.Domain;
using EM.Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace EM.Web.Controllers;

public class CidadeController : Controller
{
	private readonly IRepositorioAbstrato<Cidade> _repositorioCidade;
	public CidadeController(IRepositorioAbstrato<Cidade> repositorioCidade)
	{
		_repositorioCidade = repositorioCidade;
	}

	public IActionResult Index()
	{
		IEnumerable<Cidade> listaCidade = _repositorioCidade.GetAll();
		return View(listaCidade);
	}


	public IActionResult CadastreCidade(int? id)
	{
		if (id != null)
		{
			Cidade? cidade = _repositorioCidade.Get(c => c.ID_Cidade == id).FirstOrDefault();

			ViewBag.IsEdicao = true;
			return View(cidade);
		}
		ViewBag.IsEdicao = false;
		return View(new Cidade());
	}


	[HttpPost]
	public IActionResult CadastreCidade(Cidade cidade)
	{
		if (ModelState.IsValid)
		{
			if (cidade.ID_Cidade > 0)
			{
				_repositorioCidade.Update(cidade);
			}
			else
			{
				_repositorioCidade.Add(cidade);
			}
			return RedirectToAction("Index");
		}
		return View(cidade);
	}
}

EM.Web/Controllers/HomeController.cs
using EM.Domain;
using EM.Repository;
using Microsoft.AspNetCore.Mvc;

namespace EM.Web.Controllers;

public class HomeController : Controller
{
	private readonly RepositorioAluno _repositorioAluno = new();
	public IActionResult Index()
	{
		IEnumerable<Aluno> listaAlunos = _repositorioAluno.GetAll();
		return View(listaAlunos);
	}

}

EM.Web/Controllers/RelatorioController.cs
using EM.Domain;
using EM.Domain.Enums;
using EM.Domain.Interfaces;
using EM.Web.Controllers.Utilitarios;
using Microsoft.AspNetCore.Mvc;

namespace EM.Web.Controllers;

public class RelatorioController : Controller
{
	private readonly IRepositorioAbstrato<Cidade> _repositorioCidade;
	private readonly IRepositorioAbstrato<Aluno> _repositorioAluno;
	private readonly TabelaRelatorio _tabelaRelatorio;

	public RelatorioController(IRepositorioAbstrato<Cidade> repositorioCidade, IRepositorioAbstrato<Aluno> repositorioAluno, TabelaRelatorio tabelaRelatorio)
	{
		_repositorioCidade = repositorioCidade;
		_repositorioAluno = repositorioAluno;
		_tabelaRelatorio = tabelaRelatorio;
	}
	public IActionResult RelatorioAluno()
	{
		ViewBag.cidades = _repositorioCidade.GetAll().ToList();
		return View("/Views/Aluno/RelatorioAluno.cshtml");
	}
	public IActionResult LimpeFiltros()
	{
		return RedirectToAction(nameof(RelatorioAluno));
	}

	public IActionResult GereRelatorio()
	{
		List<Aluno> alunos = _repositorioAluno.GetAll().ToList();

		byte[] pdfBytes = _tabelaRelatorio.GereRelatorio(alunos, null, null, false, null);

		return File(pdfBytes, "application/pdf");
	}

	[HttpPost]
	public IActionResult GereRelatorio(int? ID_Cidade, Sexo? sexo, string ordem, string? uf, bool linhasZebradas, string horizontal)
	{
		List<Aluno> alunos = _repositorioAluno.GetAll().ToList();

		alunos = _tabelaRelatorio.ApliqueFiltros(alunos, ID_Cidade, sexo, ordem, uf);

		byte[] pdfBytes = _tabelaRelatorio.GereRelatorio(alunos, sexo, uf, linhasZebradas, horizontal);

		return File(pdfBytes, "application/pdf");
	}
}

EM.Web/Views/Aluno/CadastreAluno.cshtml
@using EM.Domain
@using EM.Domain.Enums
@model EM.Domain.Aluno
@{
	bool isEdicao = ViewBag.IsEdicao ?? false;
	string titulo = isEdicao ? "Editar Aluno" : "Cadastrar Aluno";

	ViewData["Title"] = titulo;
}

<div class="dev-form">
	<form class="row g-3 needs-validation" asp-controller="Aluno" asp-action="CadastreAluno" method="post" novalidate>
		<h1 class="text-center">@ViewData["Title"]</h1>
		<input type="hidden" asp-for="Matricula" />
		<input type="hidden" id="isEdicao" name="isEdicao" value="@isEdicao" />
		<div>
			<label asp-for="Nome" for="inputNome" class="form-label">Nome</label>
			<input asp-for="Nome" type="text" maxlength="100" class="form-control" name="Nome" id="Nome" placeholder="Nome" required>
			<span asp-validation-for="Nome" class="text-danger"></span>
			<div class="invalid-feedback">
				Nome deve ser preenchido
			</div>
		</div>
		<div>
			<label asp-for="CPF" for=" inputCPF" class="form-label">CPF</label>
			<input asp-for="CPF" oninput="mascara(this)" class="form-control col-md-2" name="CPF" id="CPF" placeholder="XXX.XXX.XXX-XX">
			<span asp-validation-for="CPF" class="text-danger"></span>
		</div>
		<div>
			<label asp-for="DataNascimento" class="form-label">Data de Nascimento</label>
			<input asp-for="DataNascimento" type="date" class="form-control" id="DataNascimento" name="DataNascimento"
				   value="@(isEdicao ? Model.DataNascimento.ToString("yyyy-MM-dd") : "")"
				   max="@DateTime.Now.ToString("yyyy-MM-dd")" required>
			<div class="invalid-feedback">
				Data deve ser preenchida
			</div>
		</div>
		<div class="col-md-6">
			<label asp-for="Cidade" for="inputCidade" class="form-label">Cidade</label>
			<select asp-for="Cidade" id="Cidade_ID_Cidade" class="form-select" name="Cidade.ID_Cidade" required>
				<option selected disabled value="">Selecione</option>
				@foreach (var cidade in ViewBag.Cidades)
				{
					if (Model.Cidade != null && Model.Cidade.ID_Cidade == cidade.ID_Cidade)
					{
						<option value="@cidade.ID_Cidade" selected>@cidade.Nome - @cidade.UF</option>
					}
					else
					{
						<option value="@cidade.ID_Cidade">@cidade.Nome - @cidade.UF</option>
					}
				}
			</select>
			<div class="invalid-feedback">
				Selecione uma cidade
			</div>
		</div>
		<div class="col-md-6">
			<label asp-for="Sexo" for="inputSexo" class="form-label">Sexo</label>
			@if (!isEdicao)
			{
				<select id="Sexo" name="Sexo" class="form-select" required>
					<option value="" selected>Selecione</option>
					@{
						<option value="0">Masculino</option>
						<option value="1">Feminino</option>
					}
				</select>
			}
			else
			{
				<select asp-for="Sexo" id="inputSexo" class="form-select" name="Sexo" required>
					<option selected disabled value="">Selecione</option>
					@foreach (var sexo in Enum.GetValues(typeof(Sexo)))
					{
						<option value="@sexo">@sexo</option>
					}
				</select>
			}
			<div class="invalid-feedback">
				Selecione um Sexo
			</div>
		</div>
		<div class="col-12">
			<button type="submit" class="btn botao-btn-azul">Salvar</button>
			<a class="btn botao-btn-cinza" asp-controller="Home" asp-action="Index">Voltar</a>
		</div>
	</form>
</div>

EM.Web/Views/Aluno/RelatorioAluno.cshtml
@using EM.Domain
@using EM.Domain.Enums
@model EM.Domain.Aluno
@{
	ViewData["Title"] = "Relatório";
}

<h1 style="text-align:center;">Relatório de Alunos</h1>

<div class="dev-form">
	<form class="row g-3 needs-validation" role="GereRelatorio" action="Relatorio/GereRelatorio" method="post" target="_blank">
		<div>
			<label for="Estado">Filtro por Estado</label>
			<select name="Uf" class="form-select">
				<option selected value="">Selecione</option>
				@foreach (var uf in Enum.GetValues(typeof(UF)))
				{
					<option value="@uf">@uf</option>
				}
			</select>
		</div>
		<div class="col-md-6">
			<label for="Sexo">Filtro por Sexo</label>
			<select name="Sexo" class="form-select">
				<option value="" selected>Selecione</option>
				@foreach (var obj in Enum.GetValues(typeof(Sexo)))
				{
					<option value="@obj">@obj</option>
				}
			</select>
		</div>
		<div class="col-md-6">
			<label for="ordem">Ordenar</label>
			<select id="ordem" name="ordem" class="form-select">
				<option selected>Selecione</option>
				<option value="Nome">Nome</option>
				<option value="Cidade">Cidade</option>
				<option value="UF">Estado</option>
			</select>
		</div>
		<div>
			<div class="form-check form-switch">
				<input class="form-check-input" type="checkbox" name="linhasZebradas" autocomplete="off" value="true"  id="linhaZebrada">
				<label class="form-check-label" for="linhaZebrada">Linhas zebradas</label>
			</div>
			<div class="form-check form-switch">
				<input class="form-check-input" type="checkbox" name="horizontal" autocomplete="off" value="horizontal" id="horizontal">
				<label class="form-check-label" for="horizontal">Horizontal</label>
			</div>
		</div>
			
		<div class=" d-flex">
			<a class="btn botao-btn-cinza"  asp-controller="Relatorio" asp-action="LimpeFiltros">Limpar Filtro</a>
			<a class="btn botao-btn-cinza" style="margin-left:3px;" asp-controller="Home" asp-action="Index">Voltar</a>
			<button type="submit" class=" ms-auto btn botao-btn-azul" asp-area="" asp-controller="Relatorio" asp-action="GereRelatorio" >Gerar Relatório</button>
		</div>
	</form>
</div>

EM.Web/Views/Cidade/CadastreCidade.cshtml
@using EM.Domain
@using EM.Domain.Enums
@model EM.Domain.Cidade
@{
	bool isEdicao = ViewBag.IsEdicao ?? false;
	string titulo = isEdicao ? "Edição de Cidade" : "Adicionar Cidade";

	ViewData["Title"] = titulo;
}

<div class="dev-form">
	<form class="row g-3 needs-validation" asp-controller="Cidade" asp-action="CadastreCidade" method="post" novalidate>
		<h1 class="text-center">@ViewData["Title"]</h1>
		<input type="hidden" asp-for="ID_Cidade" />
		<input type="hidden" id="isEdicao" name="isEdicao" value="@isEdicao" />
		<div class="col-md-6">
			<label asp-for="Nome" for="inputNome" class="form-label">Nome</label>
			<input asp-for="Nome" class="form-control" id="inputCidade" name="Nome" placeholder="Nome da Cidade" required>
			<div class="invalid-feedback">
				Nome deve ser preenchido
			</div>
		</div>
		<div class="col-md-6">
			<label asp-for="UF" for="inputEstado" class="form-label">Estado</label>
			<select asp-for="UF" id="inputEstado" class="form-select" name="UF" required>
				<option selected disabled value="">Estado</option>
				@foreach (var uf in Enum.GetValues(typeof(UF)))
				{
					<option value="@uf">@uf</option>
				}
			</select>
			<div class="invalid-feedback">
				Selecione uma UF
			</div>
		</div>
		<div class="col-12">
			<button type="submit" class="btn botao-btn-azul">Salvar</button>
			<a class="btn botao-btn-cinza" asp-controller="Cidade" asp-action="Index">Voltar</a>
		</div>
	</form>
</div>

EM.Web/Views/Cidade/Index.cshtml
@using EM.Domain
@{
	ViewData["Title"] = "Cadastre Cidade";
}

<div class="row">
	<div class="col-6">
		<h2>Tabela de Cidades</h2>
	</div>
	<div class="col text-end">
		<a type="button" class="btn botao-btn-azul" asp-controller="Cidade" asp-action="CadastreCidade">Adicionar Cidade</a>
	</div>
</div>
<hr>

<div class="col-md-6 mx-auto">
	<table class="table table-striped table-hover table-bordered ">
		<thead class="oi">
			<tr>
				<th class="col-1">Cidade</th>
				<th class="col-1">UF</th>
				<th class="col-1">Opção</th>
			</tr>
		</thead>

		<tbody class="dev-container">
			@foreach (Cidade cidade in Model)
			{
				<tr>
					<td>@cidade.Nome</td>
					<td>@cidade.UF</td>
					<td>
						<a type="button" class="btn botao-btn-azul" href="@Url.Action("CadastreCidade", "Cidade", new { id = cidade.ID_Cidade })">Editar</a>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>

EM.Web/Views/Home/Index.cshtml
@using EM.Repository
@using EM.Domain
@{
	ViewData["Title"] = "Home Page";
}

<!--Inicio-->
<div class="row">
	<div class="col-6">
		<h2>Tabela de Alunos </h2>
	</div>
	<div class="col text-end">
		<a type="button" class="btn botao-btn-azul" asp-controller="Aluno" asp-action="CadastreAluno">Adicionar Aluno</a>
	</div>
</div>
<hr>

<!--checkbox-->
<div class="d-flex align-items-center">
	<div class="form-check-inline">
		<h6><strong>Opções de Busca:</strong></h6>
	</div>
	<div class="form-check-inline">
		<input class="form-check-input" type="radio" name="searchOptions" id="searchMatricula" value="matricula" onchange="updateSearchType()">
		<label class="form-check-label" for="searchMatricula">Matrícula</label>
	</div>
	<div class="form-check-inline">
		<input class="form-check-input" type="radio" name="searchOptions" id="searchNome" value="nome" onchange="updateSearchType()">
		<label class="form-check-label" for="searchNome">Nome</label>
	</div>
</div>

<!--caixaTexto-->
<div class="row">
	<form class="d-flex col-6 needs-validation" role="search" action="/Aluno/Pesquise" method="post" novalidate> 
		<input class="form-control col me-2 rounded" type="search" placeholder="Matrícula ou nome do aluno..." aria-label="Pesquise" name="TermoPesquisa" required>
		<input class="col" type="hidden" name="TipoPesquisa" id="searchType">
		<button class="btn botao-btn-azul md-1 rounded" type="submit">Buscar</button>
	</form>
	<a type="button" class="btn botao-btn-azul ms-auto" style="max-width:230px; margin-right:13px;" asp-area="" asp-controller="Relatorio" asp-action="GereRelatorio" target="_blank">Relatório de todos os alunos</a>
</div>
<p></p>

<!--Tabela-->
<table id="tabelaAlunos" class="table table-striped table-hover table-bordered">
	<thead class="oi">
		<tr>
			<th scope="col">Matrícula</th>
			<th scope="col">Nome</th>
			<th scope="col">Sexo</th>
			<th scope="col">Data de Nascimento</th>
			<th scope="col">Cidade</th>
			<th scope="col">UF</th>
			<th scope="col">CPF</th>
			<th scope="col">Opções</th>
		</tr>
	</thead>

	<tbody class="dev-container">
		@foreach (Aluno aluno in Model)
		{
			<tr class="text-center">
				<td>@aluno.Matricula</td>
				<td class="text-start">@aluno.Nome</td>
				<td>@aluno.Sexo</td>
				<td>@aluno.DataNascimento.ToString("dd/MM/yyyy")</td>
				<td>@aluno.Cidade.Nome</td>
				<td>@aluno.Cidade.UF</td>
				<td>@aluno.CPF</td>
				<td>
					<a type="button" class="btn botao-btn-azul" href="@Url.Action("CadastreAluno", "Aluno", new{ id = aluno.Matricula})">Editar</a>
					<button type="submit" class="btn botao-btn-cinza" data-bs-toggle="modal" data-bs-target="#excluir-@aluno.Matricula">Excluir</button>
				</td>
			</tr>

			<div class="modal fade" id="excluir-@aluno.Matricula" tabindex="-1" aria-labelledby="excluir" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<h1 class="modal-title fs-5" id="exampleModalLabel">Excluir</h1>
							<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
						</div>
						<div class="modal-body col-7">
							Tem certaza que deseja excluir?
						</div>
						<div class="modal-footer">
							<form asp-action="RemoveAluno" asp-controller="Aluno" method="post">
								<input type="hidden" name="matricula" value="@aluno.Matricula" />
								<button type="button" class="btn btn-secondary " data-bs-dismiss="modal">Cancelar</button>
								<button type="submit" class="btn botao-btn-azul">Excluir</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		}
	</tbody>
</table>

EM.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EM.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EM.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/escolar_manager_logo (2).png"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Tabela de Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cidade" asp-action="Index">Cadastrar Cidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Relatorio" asp-action="RelatorioAluno">Relatório</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EM.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>